services:
  immo-admin:
    image: node:20
    container_name: immo-app-admin
    working_dir: /app
    ports:
      - "8090:3000"
    volumes:
      - .:/app
    command: bash -c "npm install && npm run dev"